=head1 NAME

freebsd-cvs2git-mirror - Makefile to convert FreeBSD ports to git repository

=head1 SYNOPSIS

    > make init
    > make all

    (additionally, push to remote)
    > make init-remote GIT_REMOTE_URL=<git-url>
    > make remote GIT_REMOTE_URL=<git-url>
    > make all remote GIT_REMOTE_URL=<git-url>

=head1 DESCRIPTION

The Makefile does csup, cvscvt and git push to remote git repository for those
of you maintaining local FreeBSD ports tree.

=head1 REQUIREMENTS

=over

=item git

    > sudo pkg_add -r git

=item cvscvt

L<http://tron.homeunix.org/cvscvt/>, L<git://tron.homeunix.org/cvscvt>

    > git clone git://tron.homeunix.org/cvscvt
    > cd cvscvt
    > gmake

cp(1) or install(1) build/default/cvscvt to a directory in $PATH.

=item A remote repository (optional)

With GIT_REMOTE_URL, you can push the mirrored repository to remote host.

=back

=head1 OPTIONS

=over

=item GIT_REMOTE_URL (empty)

Optionally "git push" to remote git repository if defined.

=item CSUP_HOST (cvsup.freebsd.org)

The cvs server to contact.

=item  CSUP_FLAGS (-L2)

Additional flags to csup(1), such as "-z" to enable compression.

=back

=head1 AUTHORS

The original shell script was written by lattera L<https://github.com/lattera/nightlies>

Ported by Tomoyuki Sakurai <tomoyukis@reallyenglish.com>
