=head1 NAME

freebsd-cvs2git-mirror - Makefile to convert FreeBSD ports to git repository

=head1 SYNOPSIS

> make init
> make

=head1 DESCRIPTION

The Makefile does csup, cvscvt and git push to remote git repository for those
of you maintaining local FreeBSD ports tree.

=head1 OPTIONS

=over

=item GIT_REMOTE_URL (empty)

Optionally "git push" to remote git repository if defined.

=item CSUP_HOST (cvsup.freebsd.org)

the cvs server to contact.

=item  CSUP_FLAGS (-L2)

Additional flags to csup(1).

=back

=head1 AUTHORS

The original shell script was written by lattera L<https://github.com/lattera/nightlies>

Ported by Tomoyuki Sakurai <tomoyukis@reallyenglish.com>
